version: '3.9'

services:
  db:
    container_name: postgres_quiz
    image: postgis/postgis:12-3.1-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: on-failure

  web:
    container_name: django_quiz
    build: .
    command: python manage.py runserver 0.0.0.0:8009
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    depends_on:
      - db