# Generated by Django 4.2.5 on 2023-11-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorrectanswer',
            name='incorrect_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.TextField(),
        ),
    ]
